# fly.toml file generated for story-teller on 2023-01-15T10:42:42+01:00
app = "story-teller"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
SAVE_FOLDER = "/data/save"

[experimental]
auto_rollback = true
cmd = "./story-teller"

[mounts]
source = "data"
destination = "/data"
